### ISSUE TITLE
Create page for "Social Media Kit"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#101]
Can we create a new page for "Social Media Kit"?

We can link to that page from these 2 places:  
1.  Community Partners
2. Contribute / Spread the Word 

https://pymc-data-umbrella--98.org.readthedocs.build/en/98/2022-07_sprint/sprint_parties/community_partners.html#become-community-partner

@OriolAbril @symeneses

**Comment by OriolAbril** [comment]
closed by #102
