### ISSUE TITLE
Make more prominent:  "Social Media Toolkit"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#110]
@OriolAbril Can we make the below text more prominent?

>We are providing a [Social Media Kit](https://pymc-data-umbrella--109.org.readthedocs.build/en/109/2022-07_sprint/sprint_parties/media_kit.html#media-kit) with information for sharing with your community.

**Comment by OriolAbril** [comment]
Larger font? An admonition (important or attention labeled box)? Adding it on the right sidebar like the cheatsheet link?

**Comment by reshamas** [comment]
How about a labeled box or button?
