### ISSUE TITLE
Update the install install-pymc step in env setup

### ISSUE THREAD

**Issue by symeneses** [pymc-devs/pymc-data-umbrella#130]
There was a discussion on Discord about installing the PyMc on Windows. Looking at that, I realized we should update this [install-pymc](https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/environment_setup.html#install-pymc ) and the step 5 in [PR Tutorial](https://www.pymc.io/projects/docs/en/stable/contributing/pr_tutorial.html), because the files ending in `-py3x.yml` are not in main now.

**Comment by reshamas** [comment]
cc: @cluhmann @OriolAbril

**Comment by cluhmann** [comment]
This appears to be fixed in the [latest version of the docs](https://www.pymc.io/projects/docs/en/latest/contributing/pr_tutorial.html).  We just need to make sure that we are sharing that link (rather than the "stable" version) for now.

**Comment by OriolAbril** [comment]
We have an extended version of the pr tutorial on the sprint website. It also needs to bw updated and I think it would be best to share this one: https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/environment_setup.html

Note: installing pymc should now be the same for all operative systems, but afaik, installing all development dependencies (different than the ones needed to use pymc) is still different

**Comment by OriolAbril** [comment]
The contributing workflow in the sprint website is covered in the following docs (on mobile, copying an old slack message, not everything is 100% relevant here)

I also think we should recommend doing docstring updates to anyone who is unsure about what to do as it is relatively fast, useful and impactful to both devs and users and completely self-contained. For the docsting, we splitted the guide in 3, so now the steps are:

- https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/environment_setup.html (only needs to be followed once, preferably before the os-ws)
- https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/docstring_tutorial.html (should be followed once per docstring, that is the guide on what should the contribution be, what changes and where do they go). This is the step that depends on the type of contribution, if doing other doc changes or code changes it should not be followed, the other two are common for any code or docs girhub contribution
- https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/pr_tutorial.html (once per PR, also useful if doing contributions different than docstring ones)

**Comment by reshamas** [comment]
@symeneses We can close this, right?
