### ISSUE TITLE
table not rendering on page: social media kit

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#140]
https://pymc-data-umbrella.xyz/en/latest/2022-07_sprint/sprint_parties/media_kit.html#media-kit

**Comment by OriolAbril** [comment]
what table is not rendering? I do see a table in the social media accounts section

**Comment by OriolAbril** [comment]
This can be changed to be a table, but to do so it needs to be formatted as a markdown table.

**Comment by Rohanfizz** [comment]
@reshamas can you please assign this issue to me?

**Comment by reshamas** [comment]
Closed via #149 
#DataUmbrellaPyMCSprint
