### ISSUE TITLE
Update links in YouTube video descriptions

### ISSUE THREAD

**Issue by zbraiterman** [pymc-devs/pymc-data-umbrella#151]
How can community members best help update YouTube video descriptions for PyMC related videos on the Data Umbrella channel?  

For example, how the link (https://github.com/pymc-devs/pymc-data-umbrella/blob/main/webinars/probabilistic_programming_with_pymc/notebook.ipynb) to the Jupyter Notebook for Austin’s Intro to Probabilistic Programming with PyMC
video (https://www.youtube.com/watch?v=Qu6-_AnRCs8&t=1044s) is inactive.

@reshamas, is there a structure for these types of pull requests, like the one you’ve outlined here (https://github.com/pymc-devs/video-timestamps/issues/11)?

**Comment by reshamas** [comment]
Hi @zbraiterman, thanks for bringing this to our attention.

Link not working:
https://github.com/pymc-devs/pymc-data-umbrella/blob/main/webinars/probabilistic_programming_with_pymc/notebook.ipynb

Maybe it's this:
(a)
https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/probabilistic_programming_with_pymc/notebook.ipynb

Maybe it's this:
(b)
https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/notebook.html#probprog-pymc-nb

@OriolAbril  What's the better link to refer to?

**Comment by reshamas** [comment]
@zbraiterman If you see more broken links like this, it's fine to open up an issue here, as you just did.

We restructured the whole sprint website, so that's why the links are broken, unfortunately.

**Comment by reshamas** [comment]
@OriolAbril @symeneses 
The "Run Code" button this page doesn't work.  I am not sure how to fix that?

https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/notebook.html#probprog-pymc-nb

**Comment by OriolAbril** [comment]
> Maybe it's this:
(b)
https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/notebook.html#probprog-pymc-nb

This one, always share links to the website.

> We restructured the whole sprint website, so that's why the links are broken, unfortunately.

The links on the other webinars are not broken and never were. When restructuring I set up [redirects](https://github.com/pymc-devs/pymc-data-umbrella/blob/main/conf.py#L43-L47) so that the old links continue to work. However, as this link points to GitHub directly so setting up redirect was not possible. 

I also remember the link being fixed already after flagging this on [slack](https://smartinference.slack.com/archives/C3LQZ65RA/p1655989660963569) (link will only work if you have access to slack), could the change have been undone when adding the timestamps?

>  The "Run Code" button this page doesn't work. I am not sure how to fix that?

It is working for me, can you share a screenshot of what is happening in your case to try and see what might be going on?

**Comment by reshamas** [comment]
from slack:
>Link to webinar page in website: 
https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/index.html 
(this I can and will make sure it never breaks even if we move the notebook)

It looks like there were two separate links in the video description, one directly to the repo and one to the html file.
I do recall fixing one of them.  

Confirming that I checked all the links in Austin's video description and they all work:

> ## Key Links
> - Transcript: https://github.com/data-umbrella/event-transcripts/blob/main/2022/41-austin-pymc.md
> - Meetup Event: https://www.meetup.com/data-umbrella/events/282790294/
> - Video:  https://youtu.be/Qu6-_AnRCs8
> - GitHub repo: https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/notebook.html#probprog-pymc-nb
> 
> ## Resources
> - Jupyter Notebook: https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/probabilistic_programming_with_pymc/notebook.ipynb
> - Austin's website: https://austinrochford.com/talks.html
> - ArviZ: https://github.com/arviz-devs/arviz
> - PyMC Series of events: https://pymc-data-umbrella.xyz

**Comment by reshamas** [comment]
@OriolAbril 
Running notebook in the browser:  to discuss later, next time we meet.

**Comment by zbraiterman** [comment]
Thank you, @reshamas and @OriolAbril, for following up on this. 

Is the [Slack]([url](https://smartinference.slack.com/)) open to / useful for folks like myself?

**Comment by reshamas** [comment]
> Also, is the Slack open to / useful for users like myself?

@zbraiterman Here is more information on the PyMC slack, including the "recurring contributor" role:
https://github.com/pymc-devs/pymc/blob/main/GOVERNANCE.md#recurring-contributors

**Comment by zbraiterman** [comment]
Thank you, @reshamas, for sharing this information.

**Comment by reshamas** [comment]
@zbraiterman Thanks for opening this issue. I am closing this.
If you see any more broken links, please open up a new issue here and I'll update the links.
