### ISSUE TITLE
Wrong item in requirements

### ISSUE THREAD

**Issue by symeneses** [pymc-devs/pymc-data-umbrella#169]
In the [requirements]( https://pymc-data-umbrella.xyz/en/latest/sprint/index.html#requirements), the point 4 seems like text from a different section.

I saw this while translating the page, as I didn't understand what it's referring with `Other than these two ..`

**Comment by OriolAbril** [comment]
We probably had 2 items before that one and added the 3rd some time later without realizing there was a mention to "other than these two". 

However, I think we have to rethink that whole requirements section. Maybe the cheatsheet a little bit too. A very rough draft proposal to get started:

```
Requirements depend on the contribution you are aiming for, the only common requirement is internet access!

#### Timestamps/transcripts
* items here

#### Code or doc contribution
Note: a small subset of doc contributions only requires a subset of these requirements, see below if interested.

* github account
* python/conda env setup
* basic git

#### Translations
* Transifex account
* English+Spanish or Portuguese

#### Doc contributions (non-code depedent)
That would be for example working on the glossary or adding references to docstrings.

* Github account
* Basic git
* Markdown/rst
* Raw text editor
```

**Comment by symeneses** [comment]
PR created to updated the requirements based on your comment and the original text.
