### ISSUE TITLE
Ricardo's slides: link to pdf rather than download

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#17]
Is it possible to link directly to slides in repo or Google slides rather than requiring folks to download it?
https://pymc-data-umbrella.xyz/en/latest/webinars/contributing_to_pymc/index.html#contributing-to-pymc

@mjhajharia @OriolAbril

**Comment by mjhajharia** [comment]
done https://pymc-data-umbrella.xyz/en/latest/_static/contributing_to_pymc_slides.pdf
