### ISSUE TITLE
social media kit: is event specific

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#176]
The social media kit is event specific.

We should move this to under the event date, because the links will change for each sprint event. 
https://pymc-data-umbrella.xyz/en/latest/2022-07_sprint/sprint_parties/media_kit.html

**Comment by OriolAbril** [comment]
I think this is related to https://github.com/pymc-devs/pymc-data-umbrella/pull/189#discussion_r1118133640

**Comment by reshamas** [comment]
Referenced by #196 and #189
