### ISSUE TITLE
move "Contributing" to main header (extend main menu items by 1)

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#177]

**Comment by OriolAbril** [comment]
We need to update [conf.py](https://github.com/pymc-devs/pymc-data-umbrella/blob/main/conf.py) as explained in https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#navigation-bar-dropdown-links

**Comment by OriolAbril** [comment]
closed by #181
