### ISSUE TITLE
add social media card to Meetup events

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#18]
### Meetup Events  
- https://www.meetup.com/data-umbrella-africa2/events/283260732/
- https://www.meetup.com/data-umbrella/events/283178769

### Canva card
- https://www.canva.com/design/DAE2wqy_oYo/5IIUPRJVklAtPLrzXjBI0g/edit

@mjhajharia 
cc:  @OriolAbril

**Comment by mjhajharia** [comment]
i updated the NY one, cant update the africa one as i somehow lost organizer access to meetup, ive asked beryl to add me again

**Comment by mjhajharia** [comment]
done
