### ISSUE TITLE
Add gitpod instructions 

### ISSUE THREAD

**Issue by SangamSwadiK** [pymc-devs/pymc-data-umbrella#180]
Previous discussion: https://docs.google.com/document/d/1UHxnsyDv7raYYgUcsO2T5ItLgwgmWQYKp_uXMYoUQMQ/edit?usp=sharing

**Comment by reshamas** [comment]
@SangamSwadiK 
Let's try to get this added this week.

**Comment by reshamas** [comment]
Instructions

1. Go to this link:
https://gitpod.io/#https://github.com/pymc-devs/pymc
