### ISSUE TITLE
Translations instructions: clarify what language(s) we are translating

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#185]
## File
Update instructions here:
https://pymc-data-umbrella.xyz/pt/latest/contributing/language-translations.html

## Portuguese
- **pt**
- pt_AO (Angola)
- pt_BR (Brazil)
- pt_MZ (Mozambique)
- pt_PT (Portugal)

<img width="510" alt="Screen Shot 2023-02-04 at 4 51 26 PM" src="https://user-images.githubusercontent.com/2507232/216791019-0b22367a-bff6-4258-84c5-5d4a7c170718.png">

## Spanish
25 options!
- **es** 
- es_AR (Argentina)
- es_BO (Bolivia)
- es_CL (Chile)
-

**Comment by OriolAbril** [comment]
I like https://python-docs-es.readthedocs.io/es/3.11/CONTRIBUTING.html#a-tener-en-cuenta which comes to say:

> This translation is maintaimed by Spanish speakers from all around the globe. We don't want to tie it to any region in particular and we believe this is an extra value of its own diversity. You'll find sections in different styles and tones, we only ask not changing the style every paragraph nor using very specific regionalisms.

Extra note: we are using es and pt codes which are the general language codes and are not tied to any region.

**Comment by reshamas** [comment]
edited text:

This translation is maintained by Spanish and Portuguese speakers from all around the globe. We don't want to tie it to any region in particular and we believe this is an extra value of its own diversity. You'll find sections in different styles and tones, we only ask not changing the style every paragraph nor using very specific regionalisms.

Extra note: we are using "es" and "pt" codes which are the general language codes and are not tied to any region.

Borrowed from:  
https://python-docs-es.readthedocs.io/es/3.11/CONTRIBUTING.html#a-tener-en-cuenta

**Comment by OriolAbril** [comment]
Sounds good. Let's see if @symeneses has any extra comment

**Comment by symeneses** [comment]
I think the text is clear. 👍🏽
