### ISSUE TITLE
add Welcome Bot

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#191]
We need to add a config file which should be in the folder `.github/config.yml`

Example of one is here:  
https://github.com/data-umbrella/event-board-web/blob/main/.github/config.yml

The links to these two items will need to be updated:  
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md

**Comment by reshamas** [comment]
@BhaswatiRoy Would you be interested in picking up this issue?

**Comment by BhaswatiRoy** [comment]
Hello @reshamas 
Do we need to edit the config.yml file in this directory with the updated links?
Or a new file needs to be created? 
![image](https://user-images.githubusercontent.com/78029145/218638022-78fcdb67-7a1a-44db-a90d-5086e8e8b1fe.png)

**Comment by OriolAbril** [comment]
A new file needs to be created at https://github.com/pymc-devs/pymc-data-umbrella/tree/main/.github

**Comment by BhaswatiRoy** [comment]
And the content will be same as https://github.com/data-umbrella/event-board-web/blob/main/.github/config.yml ?
only links of CONTRIBUTING.md & CODE_OF_CONDUCT.md updated?

**Comment by reshamas** [comment]
> And the content will be same as https://github.com/data-umbrella/event-board-web/blob/main/.github/config.yml ? only links of CONTRIBUTING.md & CODE_OF_CONDUCT.md updated?

that's right.

**Comment by BhaswatiRoy** [comment]
okay I can work on this!

**Comment by reshamas** [comment]
Closed via #192
