### ISSUE TITLE
Update "About" section

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#20]
On this page: 
https://pymc-data-umbrella.xyz/en/latest/about/index.html

We should add actual text about PyMC and Data Umbrella in addition to the links that are already there.

Data Umbrella is a global community for underrepresented persons in data science.  It is a fiscally hosted project of Open Collective, a registered 501(c)(3) non-profit based in California, USA. Data Umbrella: organizes online speaker series on data science and open source, organizes sprints / hackathons, curates resources on inclusive practices.  All levels are welcome, beginners and experts.

PyMC is a probabilistic programming package for Python that allows users to fit Bayesian models using a variety of numerical methods, most notably Markov chain Monte Carlo (MCMC) and variational inference (VI). Its flexibility and extensibility make it applicable to a large suite of problems.  PyMC is a non-profit project under NumFOCUS.

cc:  @mjhajharia @OriolAbril

**Comment by mjhajharia** [comment]
done, thanks reshama
