### ISSUE TITLE
clean up transcript for Austin video "Intro to Prob. Programming with PyMC"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#206]
Page: https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/probabilistic_programming_with_pymc/transcript.md

To do:
watch the video and clean the text up in the transcript.

**Comment by anushatomar13** [comment]
Hi @reshamas  ,
I would like to work on this issue. It would be great if you could assign it to me!
Thanks

**Comment by reshamas** [comment]
@anushatomar13 Sure, go for it.

**Comment by anushatomar13** [comment]
Thanks @reshamas !
Acknowledging your instruction, I am currently addressing the task at hand. Could you please confirm if I am to generate a new transcript from the video or refine an existing one? Additionally, what format should the final transcript take? Would Google Docs be acceptable?

Thank you for your clarification.

**Comment by anushatomar13** [comment]
Hi @reshamas 
Acknowledging your instruction, I am currently addressing the task at hand. Could you please confirm if I am to generate a new transcript from the video or refine an existing one? 

Wanted to confirm if I need to work with this transcript and clean it? https://github.com/pymc-devs/pymc-data-umbrella/blob/main/locales/es/LC_MESSAGES/about/probabilistic_programming_with_pymc/transcript.po

Thank you for your clarification.

**Comment by reshamas** [comment]
This is the file which needs to be cleaned:
https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/probabilistic_programming_with_pymc/transcript.md

The preference is for contributors to submit a pull request with changes in Markdown.
If you are not familiar with Markdown or how to submit a PR, then a Google doc is ok.

**Comment by anushatomar13** [comment]
Thank you for the clarification @reshamas  !
I am on it and will submit the transcript in markdown itself, as I am familiar with it on a good level.

**Comment by anushatomar13** [comment]
Hi @reshamas ,
I have made the PR. 
Please let me know if it looks fine to you?
