### ISSUE TITLE
add page for organizers and PyMC contributors working on sprint

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#22]
Here is an example from past sprints:
https://latam2021.dataumbrella.org/organizers

Info for Beryl and me are here:
https://www.dataumbrella.org/about/team

Given how much time we all have put into this, it would be good to show the people behind it.

cc:  @mjhajharia @OriolAbril

**Comment by OriolAbril** [comment]
We had a section to showcase out team in the about page (but it was empty so far). Will check to see if it's gone 🤔

Thabks for the link with your info,  at the very least we can copy yours and the speaker bios

**Comment by mjhajharia** [comment]
i think speaker bios should remain on the webinar pages and not here

**Comment by mjhajharia** [comment]
is this ok https://pymc-data-umbrella--23.org.readthedocs.build/en/23/about/index.html?

**Comment by OriolAbril** [comment]
Page is at https://pymc-data-umbrella.xyz/en/latest/about/index.html#organizers now that we have merged the PR
