### ISSUE TITLE
add in Example PR video

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#26]
Add in video to series

https://youtu.be/NbmdFJsnuuo

cc: @mjhajharia @OriolAbril

**Comment by OriolAbril** [comment]
The embedded video in https://github.com/pymc-devs/pymc-data-umbrella/blob/main/sprint/docstring_tutorial.md needs to be updated, and the link in https://github.com/pymc-devs/pymc-data-umbrella/blob/main/sprint/index.md#sprint---resources too

**Comment by mjhajharia** [comment]
done
