### ISSUE TITLE
Consider using sphinx-codeautolink

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-data-umbrella#3]
See how arviz docs for example use it to get automatic links within the code that point to the respective API docs: https://arviz-devs.github.io/arviz/getting_started/Introduction.html. We'd need some work both here and mosly on pymc end to get it working though, see https://github.com/pymc-devs/pymc/pull/5082

**Comment by mjhajharia** [comment]
hi! sorry i somehow missed this issue, i'll see if i can make it work, else ask for help!

**Comment by mjhajharia** [comment]
i'm unsure about what to do here now @OriolAbril

**Comment by OriolAbril** [comment]
If we manage to get the API docs updated on time (the documenting where we import part, not the numpydoc thing) then I'll add it, otherwise it doesn't make much sense to bother
