### ISSUE TITLE
create issues for docstring validation errors 

### ISSUE THREAD

**Issue by mjhajharia** [pymc-devs/pymc-data-umbrella#30]
note to @mjhajharia (self)

**Comment by OriolAbril** [comment]
Still not sure what priority to assign to this. I have never used so I don't know for sure, but my hunch is that the most important changes outlined in the docstring tutorial will not be covered by it. It might make more sense to dedicate that time into deeply learning that and teach other reviewers as much as possible.

i.e. I'd very much rather have some senteces without dots at their end but having all types properly documented and rendered as links to the relevant objects being referenced

**Comment by mjhajharia** [comment]
okay that's a good point, i agree. i dont know how to make it either i checked the scikit-learn file but understood nothing useful

**Comment by mjhajharia** [comment]
alright i'll create custom issues for docstring errors i find
