### ISSUE TITLE
add office hours to sprint website

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#32]
We can add the office hours to the sprint website.

Pre-sprint Office Hours, Feb 11:
https://www.meetup.com/data-umbrella/events/283765923/

Post-sprint Office Hours, Feb 25:
https://www.meetup.com/data-umbrella/events/283766699/

@mjhajharia @OriolAbril 

Please review the Meetup events and cards and confirm the dates / times, etc are ok.
If you see any adjustments needed in the Meetup event, you should be able to edit them.
@BerylKanali and I can edit the Canva cards, if needed.

**Comment by reshamas** [comment]
FYI:
We will be adding the same office hours events to the Data Umbrella Africa Meetup group too.

**Comment by mjhajharia** [comment]
done! meetup cards look good too
