### ISSUE TITLE
add to list of "webinars"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#36]
Can we add the other two videos to the list here? Oriols' webinar is from last year. Mine is not officially a webinar, but it would be nice to have them all listed in one place. 

- Oriol's talk from last year
- Reshama's video
https://pymc-data-umbrella.xyz/en/latest/webinars/index.html

Also, we could include a link there to the "PyMC Series Playlist"
https://www.youtube.com/playlist?list=PLBKcU7Ik-ir99uTvN0315hIVLuyj4Q1Gt

**Comment by OriolAbril** [comment]
We should definitely add your video more prominently to the website, not sure about my first talk though. Given how we want the sprint to be v4 only, I think participants are probably better starting with Austin's talk directly?

**Comment by mjhajharia** [comment]
#40
