### ISSUE TITLE
Figure out how to get rid of the ads

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#45]
What's the cost and process to remove the ads?

**Comment by OriolAbril** [comment]
This is being investigated in https://github.com/pymc-devs/pymc.io/issues/34

**Comment by reshamas** [comment]
Waiting for @mjhajharia to add @twiecki as an admin so he can "claim" the repo.
Request sent 2022-07-06

**Comment by mjhajharia** [comment]
hi im so sorry i somehow missed this, thomas should be recieving an email with which he can have complete access over the domain settings

**Comment by twiecki** [comment]
@mjhajharia I see that you transferred ownership of the domain, but what's required here is ownership of the RTD.

**Comment by OriolAbril** [comment]
Just added you to readthedocs @twiecki

**Comment by twiecki** [comment]
Should be without ads now. It's actually $5 per project per month.

**Comment by reshamas** [comment]
@twiecki 
Yay, it's now without ads!!!
Thank you!
