### ISSUE TITLE
Push rights

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#50]
@OriolAbril 
Do I have push rights to this repo?  If not, can I get it?

**Comment by OriolAbril** [comment]
You already have them. You are a [core contributor](https://github.com/pymc-devs/pymc/blob/main/GOVERNANCE.md#current-core-contributors) part of the community team so you have [commit rights to community related repos](https://github.com/pymc-devs/pymc/blob/main/GOVERNANCE.md#team-structure-in-practice). You can check the permissions you have for each repo at https://github.com/orgs/pymc-devs/teams/community-core/repositories
