### ISSUE TITLE
make webinars titles in a consistent format

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#52]
https://pymc-data-umbrella.xyz/en/latest/about/index.html

"array operations" ===> "Array Operations"
"Example PR" ===> "Example Pull Request"

About PyMC
[Intuitive Bayesian Modeling with PyMC](https://pymc-data-umbrella.xyz/en/latest/about/intuitive_modeling/index.html)
[Introduction to array operations in Python](https://pymc-data-umbrella.xyz/en/latest/about/intro_to_array_operations/index.html)
[Introduction to Probabilistic Programming with PyMC](https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/index.html)
[Contributing to PyMC](https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_pymc/index.html)
[Contributing to PyMC Documentation](https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_documentation/index.html)
[Example PR to PyMC](https://pymc-data-umbrella.xyz/en/latest/about/example_pr/index.html)

**Comment by OriolAbril** [comment]
To fix this we need to update the titles in the respective `index.md` files of each folder: https://github.com/pymc-devs/pymc-data-umbrella/tree/main/about.

For example, to update the array operations one we should modify the second line of https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/intro_to_array_operations/index.md (the level 1 markdown heading).

Note 1: Some of these files are still placeholders only and need to be updated to have the details of the talk and embedded video.
Note 2: DO NOT modify any of the myst targets defined in these files. MyST targets are the `(target_id)=` pieces.

**Comment by OriolAbril** [comment]
@reshamas any title still left to fix?

**Comment by reshamas** [comment]
> @reshamas any title still left to fix?

@OriolAbril 
I did change my video to spell:  "PR" ----> "Pull Request"

**Comment by OriolAbril** [comment]
And the uppercasing on array operations in #58
