### ISSUE TITLE
rewrite Ricard's "Contributing to PyMC" description in the third person, instead of "I...."

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#53]
https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_pymc/index.html

From first time contributor to project maintainer. What is it like? In this testimonial, ~~I’ll~~ [Ricardo Vieira] revisits the steps of [his]  first ever contributions to Open Source Software, to the PyMC library. ~~I~~ [He] ~~will~~ then jumps one year into the present and ~~show~~ shows what reviewing someone else’s first time contribution looks like. Hopefully, this will help demystify open source contributions without taking any of the magic out of them!

**Comment by OriolAbril** [comment]
Update the description in https://github.com/pymc-devs/pymc-data-umbrella/blob/main/about/contributing_to_pymc/index.md. The file is written in markdown, so anyone who knows markdown can do it.
