### ISSUE TITLE
default repo image needs to be resized

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#65]
This is under "Settings".

Need to resize it:

Social preview
Upload an image to customize your repository’s social media preview.

Images should be at least 640×320px (1280×640px for best display).
[Download template](https://github.com/pymc-devs/pymc-data-umbrella/settings/og-template)

**Comment by reshamas** [comment]
Image resized and uploaded.

**Comment by OriolAbril** [comment]
I don't see any changes to the image at https://github.com/pymc-devs/pymc-data-umbrella/blob/main/_static/banner_2022_07/2020_07_banner.png
