### ISSUE TITLE
Review docstring update issue

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-data-umbrella#67]
Ref: https://github.com/pymc-devs/pymc/issues/5459

Some questions:
* Are all links still working?
* Does the checklist reflect the reality?
* Would it be better to close and open a new similar issue for the coming working sessions?

cc @reshamas @symeneses

**Comment by symeneses** [comment]
The links are working. I think it's better to review and update the checklist and continue with the same issue.
