### ISSUE TITLE
Where should async communication between participants and mentors+organizers happen?

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-data-umbrella#69]
https://pymc-data-umbrella.xyz/en/latest/sprint/faq.html#is-there-a-requirement-to-have-attended-1-of-the-working-session points to the issues on this repo to ask questions. But as I mentioned in https://github.com/pymc-devs/pymc-data-umbrella/pull/47#discussion_r900183678 in my opinion it would be best to point them to discourse.

Here is the pro/con list of reasons I came across (didn't sit to think about this intensively though):

Pro discourse:
* Single place for questions about the events themselves and about pymc installation, usage...
* Engages the wider pymc community. There are also many users on discourse who can answer questions about installation and usage and answers should generally be faster than they'd be here

Against discourse:
* Requires a new account (but one can sign in with github too)
* Is a different website and interface to github

Side note: do we want to share the mentor signup on discourse (or a pre mentor signup form to do some vetting) in order to get more mentors for the events?

**Comment by reshamas** [comment]
@OriolAbril 
We can direct people to Discourse. I don't monitor it too much, but if you or @cluhmann see a question, can tag me on it.
Where on discourse?  Should we create a thread for the "Data Umbrella PyMC Open Source Working Sessions - July/Aug 2022"

**Comment by OriolAbril** [comment]
I think the two most sensible options would be

* Create an `open source working sessions` tag and have them use the Question/v4 or Question/version-agnostic tags
* Create a subcategory Events/open source working sessions.

With alternatively also a tag that is date specific like osws_july_2022 to complement either option. I don't think we should use a date specific category.

I can't commit to answering or tagging (neither here nor on discourse though) until late July. So you and @cluhmann should be the ones to decide. That being said, discourse has the nice feature of allowing you to subscribe to both tags or categories. You can subscribe to the tag/subcategory we create for this and receive mails when a question is asked there (and not for all the other questions). That way you don't need to log in to discourse or have someone tag you to be notified of questions related to the sprint.

**Comment by reshamas** [comment]
Ok, I'll let @cluhmann set that up.

Truth is, most people don't really read stuff very carefully and will post wherever they hear about the event. So, we'll still get questions all over the place.  But, that's to be expected, and ok.

**Comment by cluhmann** [comment]
I think discourse would be good for this.  It would help increase the visibility of the sprint to "non-participants" on discourse and it would get the sprint participants onto discourse.  Both good things.  I can set up whatever category/tags we need.

**Comment by OriolAbril** [comment]
> Truth is, most people don't really read stuff very carefully

Indeed, I am already painfully well aware of this :sweat:. I keep that in mind and try to use those admonition boxes, headings, hide useful but not key details in dropdowns... but I also try to write docs thinking about people who will read them carefully (sometimes that is directly future me too, for example with the pymc governance or [sphinx-primer](https://sphinx-primer.readthedocs.io/en/latest/) website)

---

Let's create a tag then: `open-source-working-sessions` and update the link. We can add info to the link so when they click on it they go directly to creating a topic with some pre-filled tags and categories. I'd make category Questions/v4 and tag open-source-working-sessions the default. It can be changed when editing (or by us later on once posted) if it were needed. If we use that, the link would look like:

```
https://discourse.pymc.io/new-topic?category=Questions/v4&tags=open-source-working-sessions
```

Ref: https://meta.discourse.org/t/how-to-create-a-new-topic-link-with-pre-filled-information/28074

Note: @cluhmann I don't know how to create tags without also creating a new topic, so I haven't created the tag yet.

**Comment by OriolAbril** [comment]
Link updated in https://github.com/pymc-devs/pymc-data-umbrella/pull/87 but keeping the issue open as a reminder to create the tag

**Comment by OriolAbril** [comment]
Updated https://discourse.pymc.io/t/data-umbrella-jul-aug-2022-contributing-to-pymc-open-source-working-sessions/9693 to have the tag so closing the issue as tag is now created
