### ISSUE TITLE
Write up instructions on how to add: CP, contributors

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#95]
Step 1:  Fork / clone repo
Step 2:  Go to file xxx

Step 5:  copy and edit text within `:::` [3 colons]; insert text above last `::::` [4 colons]

```text
:::{grid-item}

<img alt="Image for contributor template" src="../../_static/contributors_2022_07/carlo_dll.jpeg" class="rounded-circle">

Carlo Domenico Longo de Lemos

São Paulo, São Paulo (Brazil)

[{fab}`github`](https://github.com/vitaliset)
[{fab}`linkedin-in`](https://www.linkedin.com/in/carlo-lemos)
:::
```

cc:  @symeneses @OriolAbril

**Comment by OriolAbril** [comment]
I added extensive comments to the file, they don't appear on the markdown preview or website but can be seen when reading the raw text which is what should be used to copy the template. It can help with this: https://raw.githubusercontent.com/pymc-devs/pymc-data-umbrella/main/2022-07_sprint/sprint_parties/contributors.md
